-- FOTOGRAFIA DA PRODUÇÃO, 06/10/2026 — chaves, únicos, checagens, chaves estrangeiras e os índices únicos (os de desempenho ficam de fora).
alter table public.acertos add constraint acertos_pkey PRIMARY KEY (id);
alter table public.areas_entrega add constraint areas_entrega_pkey PRIMARY KEY (id);
alter table public.areas_zonas add constraint areas_zonas_pkey PRIMARY KEY (id);
alter table public.audit_log add constraint audit_log_pkey PRIMARY KEY (id);
alter table public.baixas_pendentes add constraint baixas_pendentes_pkey PRIMARY KEY (id);
alter table public.bases_catalogo add constraint bases_catalogo_pkey PRIMARY KEY (id);
alter table public.caixa_movimentos add constraint caixa_movimentos_pkey PRIMARY KEY (id);
alter table public.caixa_movimentos add constraint caixa_movimentos_tipo_check CHECK ((tipo = ANY (ARRAY['sangria'::text, 'suprimento'::text])));
alter table public.caixas add constraint caixas_pkey PRIMARY KEY (id);
alter table public.cancelamentos add constraint cancelamentos_pkey PRIMARY KEY (id);
alter table public.cardapio_config add constraint cardapio_config_pkey PRIMARY KEY (id);
alter table public.categorias add constraint categorias_pkey PRIMARY KEY (id);
alter table public.categorias_financeiras add constraint categorias_financeiras_pkey PRIMARY KEY (id);
alter table public.clientes add constraint clientes_pkey PRIMARY KEY (id);
alter table public.clientes_nexor add constraint clientes_nexor_pkey PRIMARY KEY (id);
alter table public.compras_sem_vinculo add constraint compras_sem_vinculo_pkey PRIMARY KEY (id);
alter table public.config_loja add constraint config_loja_pkey PRIMARY KEY (loja_id);
alter table public.config_operacao add constraint config_operacao_pkey PRIMARY KEY (loja_id);
alter table public.contagens_estoque add constraint contagens_estoque_pkey PRIMARY KEY (id);
alter table public.contas_capital add constraint contas_capital_pkey PRIMARY KEY (id);
alter table public.cupom_usos add constraint cupom_usos_pkey PRIMARY KEY (id);
alter table public.cupons add constraint cupons_pkey PRIMARY KEY (id);
alter table public.cupons_fiscais add constraint cupons_fiscais_pkey PRIMARY KEY (id);
alter table public.empresas add constraint empresas_pkey PRIMARY KEY (id);
alter table public.entregador_taxas add constraint entregador_taxas_pkey PRIMARY KEY (id);
alter table public.entregadores add constraint entregadores_pkey PRIMARY KEY (id);
alter table public.estoque_unidade add constraint estoque_unidade_pkey PRIMARY KEY (id);
alter table public.fiado_movimentos add constraint fiado_movimentos_pkey PRIMARY KEY (id);
alter table public.fiado_movimentos add constraint fiado_movimentos_tipo_check CHECK ((tipo = ANY (ARRAY['debito'::text, 'credito'::text])));
alter table public.ficha_grupos add constraint ficha_grupos_pkey PRIMARY KEY (id);
alter table public.ficha_itens add constraint ficha_itens_pkey PRIMARY KEY (id);
alter table public.fichas_tecnicas add constraint fichas_tecnicas_pkey PRIMARY KEY (id);
alter table public.fichas_tecnicas add constraint fichas_tecnicas_produto_id_key UNIQUE (produto_id);
alter table public.formas_pagamento add constraint formas_pagamento_pkey PRIMARY KEY (id);
alter table public.fornecedores add constraint fornecedores_pkey PRIMARY KEY (id);
alter table public.grupos_ingredientes add constraint grupos_ingredientes_pkey PRIMARY KEY (id);
alter table public.grupos_opcoes add constraint grupos_opcoes_pkey PRIMARY KEY (id);
alter table public.indicadores_manuais add constraint indicadores_manuais_loja_id_ref_local_key UNIQUE (loja_id, ref_local);
alter table public.indicadores_manuais add constraint indicadores_manuais_pkey PRIMARY KEY (id);
alter table public.insumos add constraint insumos_pkey PRIMARY KEY (id);
alter table public.lancamentos_financeiros add constraint lancamentos_financeiros_pkey PRIMARY KEY (id);
alter table public.lancamentos_financeiros add constraint lancamentos_financeiros_tipo_check CHECK ((tipo = ANY (ARRAY['despesa'::text, 'receita'::text, 'transferencia'::text])));
alter table public.loja_versao add constraint loja_versao_pkey PRIMARY KEY (loja_id);
alter table public.lojas add constraint lojas_pkey PRIMARY KEY (id);
alter table public.lotes_estoque add constraint lotes_estoque_pkey PRIMARY KEY (id);
alter table public.lotes_financeiros add constraint lotes_financeiros_loja_id_ref_local_key UNIQUE (loja_id, ref_local);
alter table public.lotes_financeiros add constraint lotes_financeiros_pkey PRIMARY KEY (id);
alter table public.mesa_comandas add constraint mesa_comandas_pkey PRIMARY KEY (id);
alter table public.mesas add constraint mesas_pkey PRIMARY KEY (id);
alter table public.modelos_impressao add constraint modelos_impressao_pkey PRIMARY KEY (id);
alter table public.motivos_cancelamento add constraint motivos_cancelamento_pkey PRIMARY KEY (id);
alter table public.motivos_movimentacao add constraint motivos_movimentacao_pkey PRIMARY KEY (id);
alter table public.movimentacoes_estoque add constraint movimentacoes_estoque_pkey PRIMARY KEY (id);
alter table public.notas_entrada add constraint notas_entrada_pkey PRIMARY KEY (id);
alter table public.opcoes add constraint opcoes_pkey PRIMARY KEY (id);
alter table public.ordens_producao add constraint ordens_producao_pkey PRIMARY KEY (id);
alter table public.pedido_base_itens add constraint pedido_base_itens_pkey PRIMARY KEY (id);
alter table public.pedido_itens add constraint pedido_itens_pkey PRIMARY KEY (id);
alter table public.pedido_pagamentos add constraint pedido_pagamentos_pkey PRIMARY KEY (id);
alter table public.pedidos add constraint pedidos_pkey PRIMARY KEY (id);
alter table public.pedidos_base add constraint pedidos_base_pkey PRIMARY KEY (id);
alter table public.perfis add constraint perfis_cargo_check CHECK ((cargo = ANY (ARRAY['plataforma'::text, 'admin'::text, 'gerente'::text, 'operador'::text, 'caixa'::text])));
alter table public.perfis add constraint perfis_pkey PRIMARY KEY (id);
alter table public.produto_grupos add constraint produto_grupos_pkey PRIMARY KEY (id);
alter table public.produto_grupos add constraint produto_grupos_produto_id_grupo_id_key UNIQUE (produto_id, grupo_id);
alter table public.produtos add constraint produtos_pkey PRIMARY KEY (id);
alter table public.status_venda add constraint status_venda_pkey PRIMARY KEY (id);
alter table public.subcategorias_financeiras add constraint subcategorias_financeiras_pkey PRIMARY KEY (id);
alter table public.sucursais add constraint sucursais_pkey PRIMARY KEY (id);
alter table public.transferencias add constraint transferencias_pkey PRIMARY KEY (id);
alter table public.turnos add constraint turnos_pkey PRIMARY KEY (id);
alter table public.unidades_medida add constraint unidades_medida_pkey PRIMARY KEY (id);
alter table public.usuarios_sistema add constraint usuarios_sistema_pkey PRIMARY KEY (id);
alter table public.acertos add constraint acertos_conta_id_fkey FOREIGN KEY (conta_id) REFERENCES contas_capital(id);
alter table public.acertos add constraint acertos_entregador_id_fkey FOREIGN KEY (entregador_id) REFERENCES entregadores(id);
alter table public.acertos add constraint acertos_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.areas_entrega add constraint areas_entrega_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.areas_zonas add constraint areas_zonas_area_id_fkey FOREIGN KEY (area_id) REFERENCES areas_entrega(id) ON DELETE CASCADE;
alter table public.caixa_movimentos add constraint caixa_movimentos_caixa_id_fkey FOREIGN KEY (caixa_id) REFERENCES caixas(id) ON DELETE CASCADE;
alter table public.caixa_movimentos add constraint caixa_movimentos_destino_conta_id_fkey FOREIGN KEY (destino_conta_id) REFERENCES contas_capital(id);
alter table public.caixas add constraint caixas_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.caixas add constraint caixas_turno_id_fkey FOREIGN KEY (turno_id) REFERENCES turnos(id) ON DELETE SET NULL;
alter table public.cancelamentos add constraint cancelamentos_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.cancelamentos add constraint cancelamentos_motivo_id_fkey FOREIGN KEY (motivo_id) REFERENCES motivos_cancelamento(id) ON DELETE SET NULL;
alter table public.cardapio_config add constraint cardapio_config_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.categorias add constraint categorias_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.categorias_financeiras add constraint categorias_financeiras_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.clientes add constraint clientes_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.config_loja add constraint config_loja_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.config_operacao add constraint config_operacao_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.contagens_estoque add constraint contagens_estoque_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.contas_capital add constraint contas_capital_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.cupom_usos add constraint cupom_usos_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id);
alter table public.cupom_usos add constraint cupom_usos_cupom_id_fkey FOREIGN KEY (cupom_id) REFERENCES cupons(id) ON DELETE CASCADE;
alter table public.cupom_usos add constraint cupom_usos_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.cupom_usos add constraint cupom_usos_pedido_id_fkey FOREIGN KEY (pedido_id) REFERENCES pedidos(id);
alter table public.cupons add constraint cupons_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.cupons_fiscais add constraint cupons_fiscais_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.entregador_taxas add constraint entregador_taxas_entregador_id_fkey FOREIGN KEY (entregador_id) REFERENCES entregadores(id) ON DELETE CASCADE;
alter table public.entregadores add constraint entregadores_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.estoque_unidade add constraint estoque_unidade_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.fiado_movimentos add constraint fiado_movimentos_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE;
alter table public.fiado_movimentos add constraint fiado_movimentos_conta_id_fkey FOREIGN KEY (conta_id) REFERENCES contas_capital(id);
alter table public.fiado_movimentos add constraint fiado_movimentos_forma_id_fkey FOREIGN KEY (forma_id) REFERENCES formas_pagamento(id);
alter table public.fiado_movimentos add constraint fiado_movimentos_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.fiado_movimentos add constraint fiado_movimentos_pedido_id_fkey FOREIGN KEY (pedido_id) REFERENCES pedidos(id);
alter table public.ficha_grupos add constraint ficha_grupos_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.ficha_grupos add constraint ficha_grupos_pai_id_fkey FOREIGN KEY (pai_id) REFERENCES ficha_grupos(id) ON DELETE SET NULL;
alter table public.ficha_itens add constraint ficha_itens_ficha_id_fkey FOREIGN KEY (ficha_id) REFERENCES fichas_tecnicas(id) ON DELETE CASCADE;
alter table public.ficha_itens add constraint ficha_itens_insumo_id_fkey FOREIGN KEY (insumo_id) REFERENCES insumos(id);
alter table public.fichas_tecnicas add constraint fichas_tecnicas_grupo_id_fkey FOREIGN KEY (grupo_id) REFERENCES ficha_grupos(id);
alter table public.fichas_tecnicas add constraint fichas_tecnicas_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.fichas_tecnicas add constraint fichas_tecnicas_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES produtos(id) ON DELETE CASCADE;
alter table public.fichas_tecnicas add constraint fichas_tecnicas_subcategoria_id_fkey FOREIGN KEY (subcategoria_id) REFERENCES subcategorias_financeiras(id);
alter table public.formas_pagamento add constraint formas_pagamento_conta_id_fkey FOREIGN KEY (conta_id) REFERENCES contas_capital(id);
alter table public.formas_pagamento add constraint formas_pagamento_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.fornecedores add constraint fornecedores_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.grupos_ingredientes add constraint grupos_ingredientes_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.grupos_opcoes add constraint grupos_opcoes_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.insumos add constraint insumos_fornecedor_id_fkey FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id);
alter table public.insumos add constraint insumos_grupo_id_fkey FOREIGN KEY (grupo_id) REFERENCES grupos_ingredientes(id);
alter table public.insumos add constraint insumos_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.insumos add constraint insumos_subcategoria_id_fkey FOREIGN KEY (subcategoria_id) REFERENCES subcategorias_financeiras(id);
alter table public.lancamentos_financeiros add constraint lancamentos_financeiros_conta_destino_id_fkey FOREIGN KEY (conta_destino_id) REFERENCES contas_capital(id);
alter table public.lancamentos_financeiros add constraint lancamentos_financeiros_conta_id_fkey FOREIGN KEY (conta_id) REFERENCES contas_capital(id);
alter table public.lancamentos_financeiros add constraint lancamentos_financeiros_forma_id_fkey FOREIGN KEY (forma_id) REFERENCES formas_pagamento(id);
alter table public.lancamentos_financeiros add constraint lancamentos_financeiros_fornecedor_id_fkey FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id);
alter table public.lancamentos_financeiros add constraint lancamentos_financeiros_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.lancamentos_financeiros add constraint lancamentos_financeiros_subcategoria_id_fkey FOREIGN KEY (subcategoria_id) REFERENCES subcategorias_financeiras(id);
alter table public.lojas add constraint lojas_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE CASCADE;
alter table public.mesa_comandas add constraint mesa_comandas_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.mesas add constraint mesas_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.modelos_impressao add constraint modelos_impressao_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.motivos_cancelamento add constraint motivos_cancelamento_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.motivos_movimentacao add constraint motivos_movimentacao_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.movimentacoes_estoque add constraint movimentacoes_estoque_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.movimentacoes_estoque add constraint movimentacoes_estoque_motivo_id_fkey FOREIGN KEY (motivo_id) REFERENCES motivos_movimentacao(id);
alter table public.notas_entrada add constraint notas_entrada_fornecedor_id_fkey FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id);
alter table public.notas_entrada add constraint notas_entrada_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.opcoes add constraint opcoes_ficha_id_fkey FOREIGN KEY (ficha_id) REFERENCES fichas_tecnicas(id) ON DELETE SET NULL;
alter table public.opcoes add constraint opcoes_grupo_id_fkey FOREIGN KEY (grupo_id) REFERENCES grupos_opcoes(id) ON DELETE CASCADE;
alter table public.ordens_producao add constraint ordens_producao_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.pedido_base_itens add constraint pedido_base_itens_pedido_id_fkey FOREIGN KEY (pedido_id) REFERENCES pedidos_base(id) ON DELETE CASCADE;
alter table public.pedido_itens add constraint pedido_itens_pedido_id_fkey FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE;
alter table public.pedido_itens add constraint pedido_itens_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES produtos(id);
alter table public.pedido_pagamentos add constraint pedido_pagamentos_forma_id_fkey FOREIGN KEY (forma_id) REFERENCES formas_pagamento(id);
alter table public.pedido_pagamentos add constraint pedido_pagamentos_pedido_id_fkey FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE;
alter table public.pedidos add constraint pedidos_caixa_id_fkey FOREIGN KEY (caixa_id) REFERENCES caixas(id);
alter table public.pedidos add constraint pedidos_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id);
alter table public.pedidos add constraint pedidos_entregador_id_fkey FOREIGN KEY (entregador_id) REFERENCES entregadores(id);
alter table public.pedidos add constraint pedidos_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.pedidos add constraint pedidos_mesa_id_fkey FOREIGN KEY (mesa_id) REFERENCES mesas(id) ON DELETE SET NULL;
alter table public.perfis add constraint perfis_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES empresas(id);
alter table public.perfis add constraint perfis_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.perfis add constraint perfis_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id);
alter table public.produto_grupos add constraint produto_grupos_grupo_id_fkey FOREIGN KEY (grupo_id) REFERENCES grupos_opcoes(id) ON DELETE CASCADE;
alter table public.produto_grupos add constraint produto_grupos_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES produtos(id) ON DELETE CASCADE;
alter table public.produtos add constraint produtos_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES categorias(id);
alter table public.produtos add constraint produtos_insumo_id_fkey FOREIGN KEY (insumo_id) REFERENCES insumos(id);
alter table public.produtos add constraint produtos_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.status_venda add constraint status_venda_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.subcategorias_financeiras add constraint subcategorias_financeiras_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES categorias_financeiras(id) ON DELETE CASCADE;
alter table public.sucursais add constraint sucursais_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE CASCADE;
alter table public.transferencias add constraint transferencias_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.turnos add constraint turnos_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
alter table public.unidades_medida add constraint unidades_medida_loja_id_fkey FOREIGN KEY (loja_id) REFERENCES lojas(id) ON DELETE CASCADE;
CREATE INDEX ix_audit_loja ON public.audit_log USING btree (loja_id, quando DESC);
CREATE INDEX ix_audit_tab ON public.audit_log USING btree (tabela, quando DESC);
CREATE INDEX ix_ficha_itens_ficha ON public.ficha_itens USING btree (ficha_id);
CREATE UNIQUE INDEX caixas_um_aberto_por_unidade ON public.caixas USING btree (loja_id, sucursal_id) WHERE ((fechado_em IS NULL) AND (fechado_txt IS NULL));
CREATE UNIQUE INDEX idx_cli_tel ON public.clientes USING btree (loja_id, telefone) WHERE (telefone IS NOT NULL);
CREATE UNIQUE INDEX idx_cupons_cod ON public.cupons USING btree (loja_id, codigo);
CREATE UNIQUE INDEX idx_uma_matriz_por_empresa ON public.lojas USING btree (empresa_id) WHERE matriz;
CREATE UNIQUE INDEX uq_acertos_ref_loja ON public.acertos USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_areas_entrega_ref_loja ON public.areas_entrega USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_areas_zonas_ref ON public.areas_zonas USING btree (ref_local);
CREATE UNIQUE INDEX uq_baixa_pend_ref ON public.baixas_pendentes USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_base_cat_nome ON public.bases_catalogo USING btree (loja_id, lower(btrim(nome)));
CREATE UNIQUE INDEX uq_base_cat_ref ON public.bases_catalogo USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_caixa_movimentos_ref ON public.caixa_movimentos USING btree (ref_local);
CREATE UNIQUE INDEX uq_caixas_ref_loja ON public.caixas USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_cancelamentos_ref_loja ON public.cancelamentos USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_cardapio_config_ref_loja ON public.cardapio_config USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_categorias_financeiras_ref_loja ON public.categorias_financeiras USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_categorias_ref_loja ON public.categorias USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_clientes_nexor_ref_loja ON public.clientes_nexor USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_clientes_ref_loja ON public.clientes USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_compras_sem_vinculo_ref_loja ON public.compras_sem_vinculo USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_contagens_estoque_ref_loja ON public.contagens_estoque USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_contas_capital_ref_loja ON public.contas_capital USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_cupom_usos_ref_loja ON public.cupom_usos USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_cupons_fiscais_ref_loja ON public.cupons_fiscais USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_cupons_ref_loja ON public.cupons USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_entregador_taxas_ref ON public.entregador_taxas USING btree (ref_local);
CREATE UNIQUE INDEX uq_entregadores_ref_loja ON public.entregadores USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_estoque_unidade ON public.estoque_unidade USING btree (loja_id, sucursal_id, item_ref);
CREATE UNIQUE INDEX uq_estoque_unidade_ref_loja ON public.estoque_unidade USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_fiado_movimentos_ref_loja ON public.fiado_movimentos USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_ficha_grupos_ref_loja ON public.ficha_grupos USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_ficha_itens_par ON public.ficha_itens USING btree (ficha_id, insumo_id) WHERE (insumo_id IS NOT NULL);
CREATE UNIQUE INDEX uq_ficha_itens_ref ON public.ficha_itens USING btree (ref_local);
CREATE UNIQUE INDEX uq_fichas_nome ON public.fichas_tecnicas USING btree (loja_id, lower(btrim(nome))) WHERE (nome IS NOT NULL);
CREATE UNIQUE INDEX uq_fichas_tecnicas_ref_loja ON public.fichas_tecnicas USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_formas_pagamento_ref_loja ON public.formas_pagamento USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_fornecedores_ref_loja ON public.fornecedores USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_grupos_ingredientes_ref_loja ON public.grupos_ingredientes USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_grupos_opcoes_ref_loja ON public.grupos_opcoes USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_impressao_tipo ON public.modelos_impressao USING btree (loja_id, tipo);
CREATE UNIQUE INDEX uq_insumos_nome ON public.insumos USING btree (loja_id, lower(btrim(nome))) WHERE (nome IS NOT NULL);
CREATE UNIQUE INDEX uq_insumos_ref_loja ON public.insumos USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_lancamentos_financeiros_ref_loja ON public.lancamentos_financeiros USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_login_por_loja ON public.usuarios_sistema USING btree (loja_id, lower(login));
CREATE UNIQUE INDEX uq_mesa_comandas_ref_loja ON public.mesa_comandas USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_mesas_ref_loja ON public.mesas USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_modelos_impressao_ref_loja ON public.modelos_impressao USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_motivo_canc_nome ON public.motivos_cancelamento USING btree (loja_id, lower(btrim(nome)));
CREATE UNIQUE INDEX uq_motivos_cancelamento_ref_loja ON public.motivos_cancelamento USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_motivos_movimentacao_ref_loja ON public.motivos_movimentacao USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_movimentacoes_estoque_ref_loja ON public.movimentacoes_estoque USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_notas_entrada_ref_loja ON public.notas_entrada USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_opcao_no_grupo ON public.opcoes USING btree (grupo_id, lower(TRIM(BOTH FROM nome)), COALESCE(preco_adicional, (0)::numeric));
CREATE UNIQUE INDEX uq_opcoes_ref ON public.opcoes USING btree (ref_local);
CREATE UNIQUE INDEX uq_ordens_producao_ref_loja ON public.ordens_producao USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_ped_base_item ON public.pedido_base_itens USING btree (pedido_id, ref_local);
CREATE UNIQUE INDEX uq_ped_base_ref ON public.pedidos_base USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_ped_itens_ref ON public.pedido_itens USING btree (pedido_id, ref_local);
CREATE UNIQUE INDEX uq_pedido_base_itens_ref ON public.pedido_base_itens USING btree (ref_local);
CREATE UNIQUE INDEX uq_pedido_itens_ref ON public.pedido_itens USING btree (ref_local);
CREATE UNIQUE INDEX uq_pedido_pagamentos_ref ON public.pedido_pagamentos USING btree (ref_local);
CREATE UNIQUE INDEX uq_pedidos_ref_loja ON public.pedidos USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_produto_grupos_ref ON public.produto_grupos USING btree (ref_local);
CREATE UNIQUE INDEX uq_produtos_nome ON public.produtos USING btree (loja_id, lower(btrim(nome))) WHERE (nome IS NOT NULL);
CREATE UNIQUE INDEX uq_produtos_ref_loja ON public.produtos USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_status_nome ON public.status_venda USING btree (loja_id, lower(btrim(nome)));
CREATE UNIQUE INDEX uq_status_venda_ref_loja ON public.status_venda USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_subcategorias_financeiras_ref ON public.subcategorias_financeiras USING btree (ref_local);
CREATE UNIQUE INDEX uq_sucursais_ref_loja ON public.sucursais USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_transferencias_ref_loja ON public.transferencias USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_turno_nome ON public.turnos USING btree (loja_id, lower(btrim(nome)));
CREATE UNIQUE INDEX uq_turnos_ref_loja ON public.turnos USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_unidades_medida_ref_loja ON public.unidades_medida USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX uq_usuarios_sistema_ref_loja ON public.usuarios_sistema USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX ux_lotes_ref ON public.lotes_estoque USING btree (loja_id, ref_local);
CREATE UNIQUE INDEX ux_pedido_pagamentos_ref ON public.pedido_pagamentos USING btree (pedido_id, ref_local);
