-- ============================================================
-- A TRILHA DE AUDITORIA EXISTIA SO EM PRODUCAO (RDS 22)
--
-- `audit_log`, `tg_auditar()` e `tg_audit_imutavel()` rodam no banco da
-- Jolo desde sempre e sao a base do `/historico` da API. Mas a definicao
-- delas nao estava em NENHUMA migracao deste repositorio: existiam
-- apenas como estado de producao.
--
-- Tres consequencias, todas ruins:
--
--  1. A migracao `20260929_indicadores_manuais.sql` faz
--     `create trigger ... execute function tg_auditar()` — ou seja, so
--     roda num banco que JA tenha a funcao. Um banco novo (copia para
--     homologacao, restauracao do zero) falharia ali.
--  2. Nao havia como revisar, comparar ou provar a trava de imutabilidade
--     para a RDS. "Confie, esta ligada" nao e evidencia.
--  3. Um banco novo nasceria SEM auditoria nenhuma, em silencio.
--
-- Esta migracao e a fotografia do que ja esta rodando, tirada do proprio
-- banco em 30/09/2026 (`pg_get_functiondef`, `pg_indexes`,
-- `pg_get_triggerdef`). Ela nao muda comportamento nenhum em producao:
-- tudo aqui e `if not exists` ou `create or replace` com o mesmo corpo.
--
-- ---------- o que a trilha guarda ----------
-- quando, loja, usuario (uuid e e-mail), cargo, tabela, operacao,
-- id do registro, ref_local, e o ANTES e o DEPOIS inteiros em jsonb.
-- Hoje sao 35 tabelas de negocio auditadas.
--
-- ---------- e o que ela NUNCA guarda ----------
-- A lista `sensiveis` dentro de `tg_auditar` tira senha, token, chave de
-- API, segredo do Meta e sessao do antes e do depois. De campo sensivel
-- fica registrado QUE mudou — "(alterado)" — e nunca o valor. Auditoria
-- que copia senha vira o maior vazamento do sistema.
--
-- ---------- honestidade sobre a imutabilidade ----------
-- `tg_audit_imutavel` bloqueia UPDATE e DELETE na trilha. Ela e forte
-- contra a aplicacao e contra qualquer usuario logado — mas o dono do
-- banco pode desligar o gatilho e religar depois, e isso ja aconteceu
-- uma vez (27/08/2026, na limpeza de 291.063 linhas registrada em
-- RESTAURACAO.md). Quem promete "nem o dono apaga" esta prometendo o que
-- o Postgres nao entrega: isso exige copia fora do banco.
-- ============================================================

-- ---------- a tabela ----------
create table if not exists public.audit_log(
  id            bigint generated by default as identity primary key,
  quando        timestamptz not null default now(),
  loja_id       uuid,
  usuario       uuid,
  usuario_email text,
  cargo         text,
  tabela        text not null,
  operacao      text not null,
  registro_id   uuid,
  ref_local     text,
  antes         jsonb,
  depois        jsonb
);
alter table public.audit_log enable row level security;

create index if not exists ix_audit_loja on public.audit_log (loja_id, quando desc);
create index if not exists ix_audit_tab  on public.audit_log (tabela,  quando desc);

-- ---------- quem le ----------
-- Le quem e da empresa; a plataforma le tudo. Ninguem escreve pela API:
-- a unica escrita vem do gatilho, que roda como dono da funcao.
drop policy if exists "le a auditoria da minha empresa" on public.audit_log;
create policy "le a auditoria da minha empresa" on public.audit_log
  for select to authenticated
  using ((select sou_plataforma()) or loja_id = (select minha_loja()));

-- ---------- id que nao estoura ----------
-- `ref_local` e texto e nem sempre e um uuid. Converter direto derrubaria
-- o gatilho e, com ele, a propria gravacao que ele audita.
create or replace function public.begin_id(t text)
 returns uuid
 language plpgsql
 immutable
 set search_path to 'public'
as $function$
begin return t::uuid; exception when others then return null; end $function$;

-- ---------- o gatilho que grava ----------
create or replace function public.tg_auditar()
 returns trigger
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare r record; lj uuid; em text; jantes jsonb; jdepois jsonb; k text;
  sensiveis text[] := array[
    'senha','senha_hash','token','access_token','refresh_token',
    'api_key','apikey','chave','chave_api','secret','app_secret',
    'meta_token','meta_app_secret','webhook_token','verify_token',
    'sessao','session','credencial','credenciais','qr','qrcode'];
begin
  -- gravacao que nao mudou nada nao e alteracao: nao ha o que auditar
  if tg_op = 'UPDATE' and to_jsonb(old) = to_jsonb(new) then
    return new;
  end if;

  r := coalesce(new, old);
  begin lj := (to_jsonb(r)->>'loja_id')::uuid; exception when others then lj := null; end;
  select email into em from auth.users where id = auth.uid();

  jantes  := case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) end;
  jdepois := case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) end;

  foreach k in array sensiveis loop
    -- registra apenas QUE houve alteracao, nunca o valor
    if jantes ? k or jdepois ? k then
      if tg_op = 'UPDATE'
         and (jantes->>k) is distinct from (jdepois->>k) then
        jdepois := jsonb_set(coalesce(jdepois,'{}'::jsonb), array[k],
                             to_jsonb('(alterado)'::text));
      elsif jdepois ? k then
        jdepois := jdepois - k;
      end if;
      jantes := jantes - k;
    end if;
  end loop;

  insert into audit_log(loja_id, usuario, usuario_email, cargo, tabela, operacao,
                        registro_id, ref_local, antes, depois)
  values (lj, auth.uid(), em, (select cargo from perfis where id = auth.uid()),
    tg_table_name, tg_op, begin_id(to_jsonb(r)->>'id'), to_jsonb(r)->>'ref_local',
    jantes, jdepois);
  return coalesce(new, old);
end $function$;

-- ---------- a trava ----------
create or replace function public.tg_audit_imutavel()
 returns trigger
 language plpgsql
 set search_path to 'public'
as $function$
begin
  raise exception 'a trilha de auditoria não pode ser alterada nem apagada'
    using errcode = 'check_violation';
end $function$;

drop trigger if exists tg_audit_imutavel on public.audit_log;
create trigger tg_audit_imutavel
  before update or delete on public.audit_log
  for each row execute function public.tg_audit_imutavel();

-- ============================================================
-- AS 35 TABELAS AUDITADAS
--
-- A lista esta escrita, e nao descoberta por varredura, de proposito:
-- tabela nova entra na auditoria por decisao, nao por acidente. E uma
-- tabela que sair desta lista aparece no `git diff` — que e exatamente o
-- que se quer de uma trilha de auditoria.
--
-- O `do` e idempotente: so cria o gatilho onde a tabela existe e onde
-- ele ainda nao esta.
-- ============================================================
do $auditar$
declare t text;
  alvos text[] := array[
    'app_usuarios','baixas_pendentes','bases_catalogo','caixas','cancelamentos',
    'clientes_nexor','config_loja','contagens_estoque','contas_capital','cupons',
    'estoque_unidade','fiado_movimentos','ficha_itens','fichas_tecnicas',
    'fiscal_config','formas_pagamento','indicadores_manuais','insumos',
    'lancamentos_financeiros','lojas','motivos_cancelamento','movimentacoes_estoque',
    'notas_entrada','ordens_producao','pedido_base_itens','pedidos','pedidos_base',
    'perfis','produtos','sucursais','sucursal_permissoes','transferencias','turnos',
    'usuarios_sistema','whatsapp_config'];
begin
  foreach t in array alvos loop
    if to_regclass('public.'||t) is null then continue; end if;
    if exists (select 1 from pg_trigger g
                join pg_class c on c.oid = g.tgrelid
                join pg_namespace n on n.oid = c.relnamespace
               where n.nspname='public' and c.relname=t
                 and g.tgname='tg_auditar' and not g.tgisinternal) then
      continue;
    end if;
    execute format(
      'create trigger tg_auditar after insert or update or delete on public.%I '||
      'for each row execute function public.tg_auditar()', t);
  end loop;
end $auditar$;
